### ISSUE TITLE
I don't think it's legal to redistribute chrome...

### ISSUE THREAD

**Issue by bwbw223** [edward789121/NoOS#1]

**Comment by edward789121** [comment]
Well it's free, so idk

**Comment by bybb** [comment]
chrome is copyrighted, you can't just go around sharing the exe, and just because it's free doesn't mean you can share the exe. I would recommend removing it becuase Google have the right to file a DMCA takedown.

**Comment by bybb** [comment]
Also the chrome exe isn't standalone, cosider adding a "download chrome" script.

**Comment by bybb** [comment]
Plus chrome isn't under the CC BY NC SA license, so claiming that you MADE chrome is a big no-bo...
